### ISSUE TITLE
typos in compare_mt.py

### ISSUE THREAD

**Issue by YueDongCS** [neulab/jsalt2019-informal#2]
I am having trouble to run_compare_mt.py, is it a typo in line 12:

p.add_argument("langpair", help="what language pair to use (e.g. fr-en)", type=str)
should be 
p.add_argument("--langpair", help="what language pair to use (e.g. fr-en)", type=str)?

**Comment by neubig** [comment]
The language pair is a required argument, so you definitely need to set it. The below usage should work:

    compare_mt.py fr-en --aligner fa

Alternatively, this should also work:

    compare_mt.py --langpair fr-en --aligner fa

**Comment by YueDongCS** [comment]
Thanks and yes, I mean the "--" before the langpair is missing

p.add_argument("langpair", help="what language pair to use (e.g. fr-en)", type=str)

________________________________

**Comment by neubig** [comment]
For required (positional) arguments, you don't need "--" before them. It's not a bug, it's a feature :)

https://docs.python.org/3/library/argparse.html#example

**Comment by YueDongCS** [comment]
I see and you are right:) I can still run it without '--'. Thanks and the first lesson learned for today.

________________________________
